# Generated by Django 3.1.14 on 2026-08-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_auto_20250906_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='car_engine',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='car_maker',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='car_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
