# Generated by Django 5.2.5 on 2025-08-13 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0014_alter_agent_id_alter_category_id_alter_followup_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lead",
            name="description",
        ),
        migrations.AddField(
            model_name="followup",
            name="agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
