# Generated by Django 5.2.5 on 2025-08-13 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0015_remove_lead_description_followup_agent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="followup",
            name="agent",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
