# Generated by Django 5.2.5 on 2025-08-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0016_alter_followup_agent"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="service",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
