# Generated by Django 5.2.5 on 2025-08-23 19:15
from django.db import migrations

class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0019_notification"),
    ]

    operations = [
        migrations.RunSQL(
            sql=r"""
            PRAGMA foreign_keys=off;

            /* 1) Krijo tabelë të re PA public_id */
            CREATE TABLE leads_lead__new (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                first_name VARCHAR(20) NOT NULL,
                last_name VARCHAR(20) NOT NULL,
                age INTEGER NOT NULL,
                organisation_id INTEGER NULL,
                agent_id INTEGER NULL,
                category_id INTEGER NULL,
                date_added DATETIME NOT NULL,
                phone_number VARCHAR(20) NOT NULL,
                email VARCHAR(254) NOT NULL,
                profile_picture VARCHAR(100) NULL,
                converted_date DATETIME NULL,
                service VARCHAR(100) NULL,
                FOREIGN KEY(organisation_id) REFERENCES leads_userprofile(id) ON DELETE CASCADE,
                FOREIGN KEY(agent_id)        REFERENCES leads_agent(id)        ON DELETE SET NULL,
                FOREIGN KEY(category_id)     REFERENCES leads_category(id)     ON DELETE SET NULL
            );

            /* 2) Kopjo rreshtat pa kolonën public_id */
            INSERT INTO leads_lead__new
            (id, first_name, last_name, age, organisation_id, agent_id, category_id,
             date_added, phone_number, email, profile_picture, converted_date, service)
            SELECT
                id, first_name, last_name, age, organisation_id, agent_id, category_id,
                date_added, phone_number, email, profile_picture, converted_date, service
            FROM leads_lead;

            /* 3) Zëvendëso tabelat */
            DROP TABLE leads_lead;
            ALTER TABLE leads_lead__new RENAME TO leads_lead;

            PRAGMA foreign_keys=on;
            """,
            reverse_sql=r"""
            /* Rollback minimal: rikrijo kolonën si nullable */
            ALTER TABLE leads_lead ADD COLUMN public_id TEXT NULL;
            """
        ),
    ]
