# Generated by Django 5.2.5 on 2025-08-28 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0021_agentloginlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentloginlog",
            name="outside_allowed_hours",
            field=models.BooleanField(default=False),
        ),
    ]
